// packages/react/src/components/Toast/Toast.tsx
import React, { useEffect } from 'react';

export interface ToastMessage {
  id: string;
  type: 'info' | 'success' | 'warning' | 'danger';
  title: string;
  message?: string;
}

export interface ToastProps {
  toasts: ToastMessage[];
  onDismiss: (id: string) => void;
  autoDismissMs?: number;
}

export const ToastContainer: React.FC<ToastProps> = ({ toasts, onDismiss, autoDismissMs = 4000 }) => {
  useEffect(() => {
    if (toasts.length === 0 || !autoDismissMs) return;

    const timer = setTimeout(() => {
      onDismiss(toasts[0].id);
    }, autoDismissMs);

    return () => clearTimeout(timer);
  }, [toasts, onDismiss, autoDismissMs]);

  if (toasts.length === 0) return null;

  return (
    <div className="a11y-toast-container" aria-label="Notifications" role="region">
      {toasts.map(toast => {
        const isAssertive = toast.type === 'danger' || toast.type === 'warning';

        return (
          <div
            key={toast.id}
            role={isAssertive ? 'alert' : 'status'}
            aria-live={isAssertive ? 'assertive' : 'polite'}
            aria-atomic="true"
            className={`a11y-toast a11y-toast--${toast.type}`}
          >
            <div>
              <strong style={{ display: 'block' }}>{toast.title}</strong>
              {toast.message && <small style={{ color: 'var(--a11y-text-muted)' }}>{toast.message}</small>}
            </div>
            <button
              type="button"
              aria-label={`Dismiss ${toast.title} notification`}
              onClick={() => onDismiss(toast.id)}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--a11y-text-muted)',
                cursor: 'pointer',
                fontSize: '1rem',
                padding: '4px 8px',
                marginLeft: '1rem',
              }}
            >
              ✕
            </button>
          </div>
        );
      })}
    </div>
  );
};

// packages/vue/src/components/Toast/Toast.vue
<script setup lang="ts">
export interface ToastMessage {
  id: string;
  type: 'info' | 'success' | 'warning' | 'danger';
  title: string;
  message?: string;
}

defineProps<{
  toasts: ToastMessage[];
}>();

const emit = defineEmits(['dismiss']);
</script>

<template>
  <div className="a11y-toast-container" role="region" aria-label="Notifications">
    <div
      v-for="toast in toasts"
      :key="toast.id"
      :role="toast.type === 'danger' || toast.type === 'warning' ? 'alert' : 'status'"
      :aria-live="toast.type === 'danger' || toast.type === 'warning' ? 'assertive' : 'polite'"
      :class="['a11y-toast', `a11y-toast--${toast.type}`]"
    >
      <div>
        <strong style="display: block;">{{ toast.title }}</strong>
        <small v-if="toast.message" style="color: var(--a11y-text-muted);">{{ toast.message }}</small>
      </div>
      <button
        type="button"
        :aria-label="`Dismiss ${toast.title} notification`"
        style="background: none; border: none; color: var(--a11y-text-muted); cursor: pointer; padding: 4px 8px; margin-left: 1rem;"
        @click="emit('dismiss', toast.id)"
      >
        ✕
      </button>
    </div>
  </div>
</template>
