// packages/react/src/components/Combobox/Combobox.tsx
import React, { useState, useId, useRef, useEffect } from 'react';

export interface ComboboxOption {
  id: string;
  label: string;
  value: string;
}

export interface ComboboxProps {
  label: string;
  options: ComboboxOption[];
  value?: string;
  onChange?: (selected: ComboboxOption | null) => void;
  placeholder?: string;
}

export const Combobox: React.FC<ComboboxProps> = ({
  label,
  options,
  value,
  onChange,
  placeholder = 'Type to search...',
}) => {
  const [query, setQuery] = useState('');
  const [isOpen, setIsOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState<number>(-1);

  const inputId = useId();
  const listboxId = useId();
  const labelId = useId();
  const liveRegionId = useId();
  const inputRef = useRef<HTMLInputElement>(null);

  const filteredOptions = options.filter(opt =>
    opt.label.toLowerCase().includes(query.toLowerCase())
  );

  useEffect(() => {
    setActiveIndex(-1);
  }, [query]);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (!isOpen && (e.key === 'ArrowDown' || e.key === 'ArrowUp')) {
      setIsOpen(true);
      setActiveIndex(0);
      e.preventDefault();
      return;
    }

    if (!isOpen) return;

    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        setActiveIndex(prev => (prev < filteredOptions.length - 1 ? prev + 1 : 0));
        break;
      case 'ArrowUp':
        e.preventDefault();
        setActiveIndex(prev => (prev > 0 ? prev - 1 : filteredOptions.length - 1));
        break;
      case 'Enter':
        e.preventDefault();
        if (activeIndex >= 0 && activeIndex < filteredOptions.length) {
          selectOption(filteredOptions[activeIndex]);
        }
        break;
      case 'Escape':
        e.preventDefault();
        setIsOpen(false);
        setActiveIndex(-1);
        break;
      case 'Tab':
        setIsOpen(false);
        break;
    }
  };

  const selectOption = (option: ComboboxOption) => {
    setQuery(option.label);
    setIsOpen(false);
    setActiveIndex(-1);
    if (onChange) onChange(option);
  };

  const activeOptionId =
    activeIndex >= 0 && filteredOptions[activeIndex]
      ? `${listboxId}-option-${activeIndex}`
      : undefined;

  return (
    <div className="a11y-combobox-container">
      <label id={labelId} htmlFor={inputId} style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 600 }}>
        {label}
      </label>
      
      <div className="a11y-combobox-input-wrapper">
        <input
          ref={inputRef}
          id={inputId}
          type="text"
          role="combobox"
          aria-expanded={isOpen}
          aria-haspopup="listbox"
          aria-controls={listboxId}
          aria-labelledby={labelId}
          aria-autocomplete="list"
          aria-activedescendant={activeOptionId}
          className="a11y-combobox-input"
          placeholder={placeholder}
          value={query}
          onChange={e => {
            setQuery(e.target.value);
            setIsOpen(true);
          }}
          onFocus={() => setIsOpen(true)}
          onKeyDown={handleKeyDown}
        />
        
        {query && (
          <button
            type="button"
            aria-label="Clear input selection"
            onClick={() => {
              setQuery('');
              setIsOpen(false);
              if (onChange) onChange(null);
              inputRef.current?.focus();
            }}
            style={{
              position: 'absolute',
              right: '0.75rem',
              background: 'none',
              border: 'none',
              color: 'var(--a11y-text-muted)',
              cursor: 'pointer',
              fontSize: '1rem',
            }}
          >
            ✕
          </button>
        )}
      </div>

      {/* Screen reader live region update */}
      <div id={liveRegionId} className="sr-only" aria-live="polite" aria-atomic="true">
        {isOpen && `${filteredOptions.length} options available.`}
      </div>

      {isOpen && filteredOptions.length > 0 && (
        <ul
          id={listboxId}
          role="listbox"
          aria-labelledby={labelId}
          className="a11y-combobox-listbox"
        >
          {filteredOptions.map((opt, index) => {
            const optionId = `${listboxId}-option-${index}`;
            const isSelected = activeIndex === index;

            return (
              <li
                key={opt.id}
                id={optionId}
                role="option"
                aria-selected={isSelected}
                className={`a11y-combobox-option ${isSelected ? 'is-focused' : ''}`}
                onClick={() => selectOption(opt)}
                onMouseEnter={() => setActiveIndex(index)}
              >
                <span>{opt.label}</span>
                {opt.value && <small style={{ color: 'var(--a11y-text-muted)' }}>{opt.value}</small>}
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
};

// packages/vue/src/components/Combobox/Combobox.vue
<script setup lang="ts">
import { ref, computed } from 'vue';

export interface ComboboxOption {
  id: string;
  label: string;
  value: string;
}

const props = defineProps<{
  label: string;
  options: ComboboxOption[];
  placeholder?: string;
}>();

const emit = defineEmits(['select']);

const query = ref('');
const isOpen = ref(false);
const activeIndex = ref(-1);

const id = `vue-combobox-${Math.random().toString(36).substring(2, 9)}`;
const inputId = `${id}-input`;
const listboxId = `${id}-listbox`;

const filteredOptions = computed(() =>
  props.options.filter(opt => opt.label.toLowerCase().includes(query.value.toLowerCase()))
);

const handleKeyDown = (e: KeyboardEvent) => {
  if (!isOpen.value && (e.key === 'ArrowDown' || e.key === 'ArrowUp')) {
    isOpen.value = true;
    activeIndex.value = 0;
    e.preventDefault();
    return;
  }

  if (!isOpen.value) return;

  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault();
      activeIndex.value = activeIndex.value < filteredOptions.value.length - 1 ? activeIndex.value + 1 : 0;
      break;
    case 'ArrowUp':
      e.preventDefault();
      activeIndex.value = activeIndex.value > 0 ? activeIndex.value - 1 : filteredOptions.value.length - 1;
      break;
    case 'Enter':
      e.preventDefault();
      if (activeIndex.value >= 0 && activeIndex.value < filteredOptions.value.length) {
        selectOption(filteredOptions.value[activeIndex.value]);
      }
      break;
    case 'Escape':
      isOpen.value = false;
      break;
  }
};

const selectOption = (opt: ComboboxOption) => {
  query.value = opt.label;
  isOpen.value = false;
  emit('select', opt);
};
</script>

<template>
  <div className="a11y-combobox-container">
    <label :for="inputId" style="display: block; margin-bottom: 0.5rem; font-weight: 600;">
      {{ label }}
    </label>

    <div className="a11y-combobox-input-wrapper">
      <input
        :id="inputId"
        v-model="query"
        type="text"
        role="combobox"
        :aria-expanded="isOpen"
        aria-haspopup="listbox"
        :aria-controls="listboxId"
        aria-autocomplete="list"
        className="a11y-combobox-input"
        :placeholder="placeholder || 'Search options...'"
        @focus="isOpen = true"
        @keydown="handleKeyDown"
      />
    </div>

    <ul
      v-if="isOpen && filteredOptions.length"
      :id="listboxId"
      role="listbox"
      className="a11y-combobox-listbox"
    >
      <li
        v-for="(opt, index) in filteredOptions"
        :key="opt.id"
        role="option"
        :aria-selected="activeIndex === index"
        :class="['a11y-combobox-option', { 'is-focused': activeIndex === index }]"
        @click="selectOption(opt)"
        @mouseenter="activeIndex = index"
      >
        <span>{{ opt.label }}</span>
        <small style="color: var(--a11y-text-muted);">{{ opt.value }}</small>
      </li>
    </ul>
  </div>
</template>
